config/routes.rb
Rails.application.routes.draw do
  resources :rents
  resources :book_units
  resources :books
  devise_for :users
  root to: "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, :author, presence: true

  has_many :book_units, dependent: :destroy
end

app/models/book_unit.rb
class BookUnit < ApplicationRecord
  validates :condition, :edition, :year, presence: true

  belongs_to :book
  has_many :rents
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :user
  belongs_to :book_unit

  def check_generate_bill
    if rent_checked == false
      delayed_days = (self.return_date - self.created_at.to_date).to_i - self.days_to_deadline
      if delayed_days > 0
        self.user.add_bill(self.bill_day_delay * (delayed_days * bill_day_delay))
      end
      rent_checked = true
    end
  end

  def return_book_unit
    self.return_date = Date.today
    self.check_generate_bill
    self.book_unit.available = true
  end


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :rents, dependent: :destroy

  def add_bill(new_bill)
    self.bill_amount = self.bill_amount + new_bill
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/book_units_controller.rb
class BookUnitsController < ApplicationController
  before_action :set_book_unit, only: [:show, :edit, :update, :destroy]

  # GET /book_units
  # GET /book_units.json
  def index
    @book_units = BookUnit.all
  end

  # GET /book_units/1
  # GET /book_units/1.json
  def show
  end

  # GET /book_units/new
  def new
    @book_unit = BookUnit.new(book_id: params[:book_id])
  end

  # GET /book_units/1/edit
  def edit
  end

  # POST /book_units
  # POST /book_units.json
  def create
    @book_unit = BookUnit.new(book_unit_params)

    respond_to do |format|
      if @book_unit.save
        format.html { redirect_to @book_unit, notice: 'Book unit was successfully created.' }
        format.json { render :show, status: :created, location: @book_unit }
      else
        format.html { render :new }
        format.json { render json: @book_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /book_units/1
  # PATCH/PUT /book_units/1.json
  def update
    respond_to do |format|
      if @book_unit.update(book_unit_params)
        format.html { redirect_to @book_unit, notice: 'Book unit was successfully updated.' }
        format.json { render :show, status: :ok, location: @book_unit }
      else
        format.html { render :edit }
        format.json { render json: @book_unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /book_units/1
  # DELETE /book_units/1.json
  def destroy
    @book_unit.destroy
    respond_to do |format|
      format.html { redirect_to book_units_url, notice: 'Book unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book_unit
      @book_unit = BookUnit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_unit_params
      params.require(:book_unit).permit(:book_id, :available, :edition, :condition, :year)
    end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @books = Book.all
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :author, :sinopsys)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
  before_action :set_rent, only: [:show, :edit, :update, :destroy]

  # GET /rents
  # GET /rents.json
  def index
    @rents = Rent.all
  end

  # GET /rents/1
  # GET /rents/1.json
  def show
  end

  # GET /rents/new
  def new
    @rent = Rent.new
  end

  # GET /rents/1/edit
  def edit
  end

  # POST /rents
  # POST /rents.json
  def create
    @rent = Rent.new(rent_params)

    respond_to do |format|
      if @rent.save
        format.html { redirect_to @rent, notice: 'Rent was successfully created.' }
        format.json { render :show, status: :created, location: @rent }
      else
        format.html { render :new }
        format.json { render json: @rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rents/1
  # PATCH/PUT /rents/1.json
  def update
    respond_to do |format|
      if @rent.update(rent_params)
        format.html { redirect_to @rent, notice: 'Rent was successfully updated.' }
        format.json { render :show, status: :ok, location: @rent }
      else
        format.html { render :edit }
        format.json { render json: @rent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rents/1
  # DELETE /rents/1.json
  def destroy
    @rent.destroy
    respond_to do |format|
      format.html { redirect_to rents_url, notice: 'Rent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_rent
      @rent = Rent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def rent_params
      params.require(:rent).permit(:user_id, :book_id, :days_to_deadline, :bill_day_delay)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_units_helper.rb
module BookUnitsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/rents_helper.rb
module RentsHelper
end

app/views/book_units/_form.html.erb
<%= form_with(model: book_unit, local: true) do |form| %>
  <% if book_unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book_unit.errors.count, "error") %> prohibited this book_unit from being saved:</h2>

      <ul>
      <% book_unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form.hidden_field :book_id %>

  <div class="field">
    <%= form.label :available %>
    <%= form.check_box :available, id: :book_unit_available %>
  </div>

  <div class="field">
    <%= form.label :edition %>
    <%= form.text_field :edition, id: :book_unit_edition %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year, id: :book_unit_year %>
  </div>

  <div class="field">
    <%= form.label :condition %>
    <%= form.text_field :condition, id: :book_unit_condition %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/book_units/edit.html.erb
<h1>Editing Book Unit</h1>

<%= render 'form', book_unit: @book_unit %>

<%= link_to 'Show', @book_unit %> |
<%= link_to 'Back', book_units_path %>

app/views/book_units/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Book Units</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Available</th>
      <th>Edition</th>
      <th>Condition</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @book_units.each do |book_unit| %>
      <tr>
        <td><%= book_unit.book.title %></td>
        <td><%= book_unit.book.author %></td>
        <td><%= book_unit.available %></td>
        <td><%= book_unit.edition %></td>
        <td><%= book_unit.condition %></td>
        <td><%= link_to 'Show', book_unit %></td>
        <td><%= link_to 'Edit', edit_book_unit_path(book_unit) %></td>
        <td><%= link_to 'Destroy', book_unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/book_units/new.html.erb
<h1>New Book Unit</h1>

<%= render 'form', book_unit: @book_unit %>

<%= link_to 'Back', book_units_path %>

app/views/book_units/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= link_to @book_unit.book.title, @book_unit.book %>
</h2>

<p>
  <strong>Author:</strong>
  <%= @book_unit.book.author %>
</p>

<p>
  <strong>Sinopsys:</strong>
  <%= @book_unit.book.sinopsys %>
</p>

<p>
  <strong>Available:</strong>
  <%= @book_unit.available %>
</p>

<p>
  <strong>Edition:</strong>
  <%= @book_unit.edition %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @book_unit.condition %>
</p>

<%= link_to 'Edit', edit_book_unit_path(@book_unit) %> |
<%= link_to 'Back', book_units_path %>

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
      <% book.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :book_title %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author, id: :book_author %>
  </div>

  <div class="field">
    <%= form.label :sinopsys %>
    <%= form.text_area :sinopsys, id: :book_sinopsys %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

app/views/books/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Available Units</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td><%= book.title %></td>
        <td><%= book.author %></td>
        <td><%= book.book_units.where(available: true).count %></td>
        <td><%= link_to 'Show', book %></td>
        <td><%= link_to 'Edit', edit_book_path(book) %></td>
        <td><%= link_to 'Destroy', book, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book', new_book_path %>

app/views/books/new.html.erb
<h1>New Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Back', books_path %>

app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<h2>
  <%= @book.title %>
</h2>

<p>
  <strong>Author:</strong>
  <%= @book.author %>
</p>

<p>
  <strong>Sinopsys:</strong>
  <%= @book.sinopsys %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

<h3>Available Book Units</h3>

<table>
  <thead>
    <tr>
      <th>Edition</th>
      <th>Condition</th>
      <th>Year</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @book.book_units.where(available: true).each do |book_unit| %>
      <tr>
        <td><%= book_unit.edition %></td>
        <td><%= book_unit.condition %></td>
        <td><%= book_unit.year %></td>
        <td><%= link_to 'Show', book_unit %></td>
        <td><%= link_to 'Edit', edit_book_unit_path(book_unit) %></td>
        <td><%= link_to 'Destroy', book_unit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Book Unit', new_book_unit_path(book_id: @book.id) %>

app/views/home/index.html.erb
<p>
<%= link_to "Books", books_path%>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibrarySystem</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <div id="container">
      <div id="user_nav">
        <% if user_signed_in? %>
          Logged in as <strong><%= current_user.email %></strong>.
          <%= link_to 'Edit profile', edit_user_registration_path %> |
          <%= link_to "Logout", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign up", new_user_registration_path %> |
          <%= link_to "Login", new_user_session_path %>
        <% end %>
      </div>
      <%= yield %>

      <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, id: "flash_#{name}" %>
      <% end %>

    </div>

  </body>
</html>

app/views/rents/_form.html.erb
<%= form_with(model: rent, local: true) do |form| %>
  <% if rent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rent.errors.count, "error") %> prohibited this rent from being saved:</h2>

      <ul>
      <% rent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :rent_user_id %>
  </div>

  <div class="field">
    <%= form.label :book_id %>
    <%= form.text_field :book_id, id: :rent_book_id %>
  </div>

  <div class="field">
    <%= form.label :days_to_deadline %>
    <%= form.number_field :days_to_deadline, id: :rent_days_to_deadline %>
  </div>

  <div class="field">
    <%= form.label :bill_day_delay %>
    <%= form.text_field :bill_day_delay, id: :rent_bill_day_delay %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rents/edit.html.erb
<h1>Editing Rent</h1>

<%= render 'form', rent: @rent %>

<%= link_to 'Show', @rent %> |
<%= link_to 'Back', rents_path %>

app/views/rents/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rents</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Book</th>
      <th>Days to deadline</th>
      <th>Bill day delay</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rents.each do |rent| %>
      <tr>
        <td><%= rent.user %></td>
        <td><%= rent.book %></td>
        <td><%= rent.days_to_deadline %></td>
        <td><%= rent.bill_day_delay %></td>
        <td><%= link_to 'Show', rent %></td>
        <td><%= link_to 'Edit', edit_rent_path(rent) %></td>
        <td><%= link_to 'Destroy', rent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Rent', new_rent_path %>

app/views/rents/new.html.erb
<h1>New Rent</h1>

<%= render 'form', rent: @rent %>

<%= link_to 'Back', rents_path %>

app/views/rents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @rent.user %>
</p>

<p>
  <strong>Book:</strong>
  <%= @rent.book %>
</p>

<p>
  <strong>Days to deadline:</strong>
  <%= @rent.days_to_deadline %>
</p>

<p>
  <strong>Bill day delay:</strong>
  <%= @rent.bill_day_delay %>
</p>

<%= link_to 'Edit', edit_rent_path(@rent) %> |
<%= link_to 'Back', rents_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>